import { sql } from "drizzle-orm";

// We don't define the table here as it's in the storage schema,
// but we execute the SQL to create policies.

// biome-ignore lint/suspicious/noExplicitAny: Dynamic DB type for migration
export async function up(db: any) {
	// Enable RLS on storage.objects if not already enabled
	await db.execute(sql`alter table storage.objects enable row level security;`);

	// Policy: Authenticated users can upload to 'attachments' bucket
	// We restrict uploads to the 'attachments' bucket and ensure the user owns the folder (optional, but good practice)
	// For simplicity, we'll allow any authenticated user to upload to 'attachments'
	await db.execute(sql`
        create policy "Authenticated users can upload attachments"
        on storage.objects for insert
        to authenticated
        with check ( bucket_id = 'attachments' );
    `);

	// Policy: Users can view their own uploads (or public definition)
	// But since our bucket is private, we control view access via Signed URLs generated by backend.
	// However, the uploader might need to see it immediately?
	// Actually, createSignedUrl is done via backend usually or service role.
	// If we want frontend to download, they need a signed URL.

	// Let's add policy for viewing just in case, though signed URLs bypass RLS if created with service role?
	// "Signed URLs are valid for a specified duration... This allows you to grant temporary access... without making the file permanently public."
	// Signed URLs generated with SERVICE key bypass RLS.
	// Signed URLs generated with ANON key respect RLS.
	// We will generate signed URLs in the backend using the service role (or just standard authenticated client if policy allows).

	// Policy: Allow users to read files in attachments bucket
	// For stricter security, we could limit to "owner" logic, but "requests" are shared across roles.
	// So we'll rely on the Application Level (Backend) to generate Signed URLs for authorized users.
	// The backend uses the Service Role (or has access), so it can generate Signed URLs even if RLS denies "select".
	// WAIT: createSignedUrl does NOT check RLS at generation time, but the access token inside the URL might?
	// No, Service Role generated signed URLs allow access.

	// So we just need Insert permissions for 'authenticated' role.
}
